#    Consider the below code to answer further questions:
# import numpy as np
# list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
# array_list = np.array(object = list_)

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

## Answer :-> 

### The names list_ and array_list in Python don't inherently imply a difference in data types. These are variable names, and their specific data types depend on what values are assigned to them during the program execution.

### By convention, the name list_ could imply a list data type, and array_list could imply a list or an array-like structure, but these names alone don't enforce a specific data type.

#### For example, both list_ and array_list could be assigned as lists in Python:

In [2]:
list_ = [1, 2, 3]  # list_ is assigned as a list
array_list = ["a", "b", "c"]  # array_list is also assigned as a list

In [3]:
# Print the data types of both variables
print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {type(array_list)}")

Data type of list_: <class 'list'>
Data type of array_list: <class 'list'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

# Answer :->

In [10]:
import numpy as np
# Define the list_ variables
list_ = [1, 2, 3, "hello", 5.5 ,"hii" , 80.06 ,"wajid" , 'bye' , 373 , '372' ]
print("Data types in list_:")
for i in list_:
    print(f"Data Type of {(i)} is : {type(i)}")
    

Data types in list_:
Data Type of 1 is : <class 'int'>
Data Type of 2 is : <class 'int'>
Data Type of 3 is : <class 'int'>
Data Type of hello is : <class 'str'>
Data Type of 5.5 is : <class 'float'>
Data Type of hii is : <class 'str'>
Data Type of 80.06 is : <class 'float'>
Data Type of wajid is : <class 'str'>
Data Type of bye is : <class 'str'>
Data Type of 373 is : <class 'int'>
Data Type of 372 is : <class 'str'>


In [11]:
# Define array_list variables
array_list = np.array([1, 2, 3, 4, 5])
print("\nData types in array_list:")
for i in array_list:
    print(f"Data Type of {(i)} is : {type(i)}")


Data types in array_list:
Data Type of 1 is : <class 'numpy.int64'>
Data Type of 2 is : <class 'numpy.int64'>
Data Type of 3 is : <class 'numpy.int64'>
Data Type of 4 is : <class 'numpy.int64'>
Data Type of 5 is : <class 'numpy.int64'>


# Q3. Considering the following changes in the variable, array_list:
## array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [12]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [13]:
# Answer :->
array_list = np.array(object = list_, dtype = int)

### The original list_ contains strings ('1', '2', '3', '4', '5'). When you create array_list with dtype=int, NumPy will attempt to convert these strings into integers.

### Here are the data types of elements in both variables:

#### Original List (list_)
##### Elements: Strings ('1', '2', '3', '4', '5')


#### NumPy Array (array_list) with dtype=int
##### Elements: Integers (1, 2, 3, 4, 5)

In [14]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
print("Data types in list_:")
for i in list_:
    print(f"Data Type of {(i)} is : {type(i)}")

Data types in list_:
Data Type of 1 is : <class 'str'>
Data Type of 2 is : <class 'str'>
Data Type of 3 is : <class 'str'>
Data Type of 4 is : <class 'str'>
Data Type of 5 is : <class 'str'>


In [15]:
array_list = np.array(object = list_, dtype = int)
print("\nData types in array_list:")
for i in array_list:
    print(f"Data Type of {(i)} is : {type(i)}")


Data types in array_list:
Data Type of 1 is : <class 'numpy.int64'>
Data Type of 2 is : <class 'numpy.int64'>
Data Type of 3 is : <class 'numpy.int64'>
Data Type of 4 is : <class 'numpy.int64'>
Data Type of 5 is : <class 'numpy.int64'>


# Q4. Write a code to find the following characteristics of variable, num_array:   (i) shape   (ii) size
## Consider the below code to answer further questions:
#### import numpy as np
#### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#### num_array = np.array(object = num_list)

In [16]:
# Answer :->
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [17]:
# (i) Finding the shape of num_array
shape_of_array = num_array.shape

# (ii) Finding the size of num_array
size_of_array = num_array.size

print("Shape of num_array:", shape_of_array)
print("Size of num_array:", size_of_array)

Shape of num_array: (2, 3)
Size of num_array: 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
## [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [18]:
import numpy as np

# Creating a 3x3 matrix filled with zeros
zeros_array = np.zeros((3, 3))

print("Array filled with zeros:")
print(zeros_array)


Array filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
## [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [19]:
import numpy as np

# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# ....................................... Thank   YOU..........................................